site_name: AI Quickstart
site_url: https://aiquickst.art

theme:
  name: material
  features:
    - navigation.instant

nav:
  - Home: index.md

  - AI with Python:
    - Overview: python/index.md
    - Onboarding: python/onboarding.md
    - Python Development with GitHub Codespaces: python/github_codespaces.md
    - GitHub Models: python/github_models.md
    - OpenAI SDK: python/openai.md
    - Interactive Development with Jupyter Notebook: python/jupyter.md
    - LangChain: python/langchain.md

extra:
  analytics:
    provider: google
    property: G-3GTSPZR1PG
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/getaiquickstart